{% set version = "9.10.1" %}
package:
  name: apache-solr
  version: {{ version }}  # Use the specific version you want to package

source:
  - url: https://github.com/apache/solr/archive/refs/tags/releases/solr/{{ version }}.tar.gz
    sha256: aa8a3517f7abc1d1b7ac86e361ee6ad4b1431e6d4151fca72e3439af687c132b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
    - openjdk =21

  run:
    - openjdk >=11  # Solr requires Java to run

test:
  commands:
    - solr start -h
    - solr stop -h

about:
  home: https://solr.apache.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: >
    Solr is highly reliable, scalable and fault tolerant, providing distributed indexing, replication and load-balanced querying, automated failover and recovery, centralized configuration and more.

extra:
  recipe-maintainers:
    - antarcticrainforest
    - mo-dkrz
    - karion
