{% set version = "9.8.0" %}
package:
  name: apache-solr
  version: {{ version }}  # Use the specific version you want to package

source:
  - url: https://github.com/apache/solr/archive/refs/tags/releases/solr/{{ version }}.tar.gz
    sha256: 5bb58d169eb31cf15307ab64a2fcc8579e2a21517a67dfc326834ad6b3f50fa1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
    - openjdk =21

  run:
    - openjdk >=11  # Solr requires Java to run

test:
  commands:
    - solr start -e cloud -noprompt
    - solr stop -all

about:
  home: https://solr.apache.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: >
    Solr is highly reliable, scalable and fault tolerant, providing distributed indexing, replication and load-balanced querying, automated failover and recovery, centralized configuration and more.

extra:
  recipe-maintainers:
    - antarcticrainforest
